### Criar baralho
GET http://localhost:3000/truco/newDeck

### Distribuir cartas
GET http://localhost:3000/truco/32i2a2sdocdq/distribuir

### Embaralhar cartas
GET http://localhost:3000/truco/32i2a2sdocdq/embaralhar